### ISSUE TITLE
Add SkeletonView as example

### ISSUE THREAD

**Issue by Juanpe** [leogdion/AWESOME-AWESOME-README#4]
Hi @leogdion! thanks for this repo. I think it's very useful for everyone 👍🏼 

I have a project and IMHO it would be a good example of a README file. The project is [SkeletonView](https://github.com/Juanpe/SkeletonView). 

What do you think? Could we include it?

Thanks! 🙂

**Comment by leogdion** [comment]
Sure! It looks nice.

Go ahead and put in a PR. Add it under the `Examples` section. 

Thank you!
